version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-management-service:
    build: .
    container_name: user-management-service
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/userdb
      - JWT_SECRET=your_jwt_secret
      - PORT=5000

volumes:
  mongo_data: